spring:
  application:
    name: ph-eureka-service-registry


eureka:
  client:
    registerWithEureka: false
    fetch-registry: false

server.port: 8761



#Sleuth
spring.sleuth.scheduled.enabled: false
spring.sleuth.async.enabled: false
spring.sleuth.annotation.enabled: false
spring.sleuth.enabled:  true
spring.sleuth.sampler.probability: 1.0
#Zipkin
spring.zipkin.baseUrl:  http://localhost:9411
spring.zipkin.sender.type: web

spring.rabbitmq.host: localhost # RabbitMQ host.
spring.rabbitmq.port: 5672 # RabbitMQ port.