spring:
  application:
    name: ph-spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/opencodes/environment-variable-repo.git
          default-label: main

server:
  port: ${port:8888}
  servlet:
    context-path: /

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

