spring.application.name: ph-product-stock-service
# Data Source
spring.datasource.url: jdbc:mysql://localhost:3306/spring_microservice
spring.datasource.username: rkjha
spring.datasource.password: Mysql@123
spring.jpa.show-sql: false
server.port: ${port:8800}
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/


spring.sleuth.sampler.percentage: 0.2