spring:
  application:
    name: ph-product-enquiry-service

server:
  port: ${port:8700}

productservice:
  ribbon:
    listOfServers: localhost:8800,localhost:8801

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
